version: '3.1'

services:

  db:
    build: .
    container_name: pg_isolation_custom
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: isolation
      POSTGRES_PASSWORD: isolation
      POSTGRES_DB: isolation