spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/isolation'
    username: isolation
    password: isolation
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    pl.kostrowski.locking: debug
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
