version: '3.1'

services:

  db:
    image: postgres:14.5
    container_name: pg_isolation_standard
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: isolation
      POSTGRES_PASSWORD: isolation
      POSTGRES_DB: isolation